Repository laminas/laminas-stdlib, pull requests merged in 2021-12, with the labels that each got.

#40 Relax dependencies and strict run on PHP 8.1
  .laminas-ci.json
  composer.json
  composer.lock
  phpbench.json
Labels: Enhancement

#39 [3.6] Regression: ArrayObject with protected ARRAY_AS_PROPS cannot be serialized anymore
  psalm-baseline.xml
  src/ArrayObject.php
  test/ArrayObjectTest.php
  test/CustomArrayObject.php
Labels: BC Break, Bug

#43 Fix #15 add test on glob and GLOB_BRACE flag
  src/Glob.php
  test/GlobTest.php
  test/_files/{alph,bet}a
Labels: Bug

#42 Fix #18 call `->toArray()` on `Traversable` instances given to `ArrayUtils::iteratorToArray()` only for instances which are **not** `Iterator` implementations
  src/ArrayUtils.php
  test/ArrayUtilsTest.php
  test/TestAsset/IteratorWithToArrayMethod.php
Labels: Bug
