Repository laminas/laminas-stdlib, pull requests merged in 2022-01, with the labels that each got.

#49 Improve psalm annotations for `SplQueue`
  psalm-baseline.xml
  src/SplQueue.php
  src/SplStack.php
Labels: Enhancement

#48 Fix docs indent in list
  docs/book/console-helper.md
Labels: Documentation, Enhancement

#52 Fixes crash in `StringUtils::registerWrapper()`
  src/StringUtils.php
  test/StringUtilsTest.php
Labels: Bug

#54 Fix for #50 - added `ReturnTypeWillChange` to `ArrayStack#getIterator()`, to comply with PHP 8.1 requirements
  phpunit.xml.dist
  src/ArrayStack.php
  test/ArrayStackTest.php
Labels: Bug
