Repository laminas/laminas-stdlib, pull requests merged in 2022-06, with the labels that each got.

#58 qa: Improve types for SplPriorityQueue
  README.md
  psalm-baseline.xml
  src/SplPriorityQueue.php
Labels: Documentation, Enhancement

#59 Improve types for `PriorityQueue`
  psalm-baseline.xml
  src/PriorityQueue.php
Labels: Enhancement

#60 Fix incorrect return type annotation when `EXTR_DATA` is used when extracting data from a `PriorityQueue`
  src/PriorityQueue.php
Labels: Bug, Documentation

#62 qa: Improve SA for `ArrayUtils::iteratorToArray()`
  src/ArrayUtils.php
Labels: Documentation, Enhancement

#63 Relax param type of `ArrayUtils::iteratorToArray`
  src/ArrayUtils.php
Labels: Bug, Documentation
